### ISSUE TITLE
Running with --no-runtime

### ISSUE THREAD

**Issue by nightuser** [flathub/com.valvesoftware.Steam.Utility.protontricks#16]
Why the recommended way of running has `--no-runtime` flag?

It gives me the following error when I try to install a package (e.g. I got it with `wmp9`):
```
0064:err:module:load_so_dll failed to load .so lib "/home/nightuser/.local/share/Steam/steamapps/common/Proton 5.0/dist/bin/../lib64/wine/winebus.sys.so": libudev.so.0: cannot open shared object file: No such file or directory
```

It doesn't fail with the runtime present.

**Comment by Matoking** [comment]
I could reproduce the issue. I don't really have a good idea of why it stopped working (could be related to Proton binaries, the 20.08 runtime update in Steam Flatpak or something else), but since running Protontricks using Steam Runtime is the ideal thing to do and actually works now, might as well drop the flag.
