### ISSUE TITLE
[Flatpak] Package does not actually show up in flatpak, seems to have some collision with com.valvesoftware.Steam

### ISSUE THREAD

**Issue by databoose** [flathub/com.valvesoftware.Steam.Utility.protontricks#18]
As said in title, when i attempt to install the flatpak package, it says everything is fine, and that it has installed, but once i check .var, the folder for protontricks is nowhere to be found, and it is neither in the flatpak list as well.

Why is the package name com.valvesoftware.Steam.Utility.protontricks ? Why can't it just be its own package and not create this convoluted mess of a problem? And why is just running the binary so difficult for literally no good reason? I should never have to add a command to bashrc just to soley use a program.

**Comment by Matoking** [comment]
Due to a bug in the Steam Flatpak, Protontricks is not working for the time being. It should be fixed once flathub/com.valvesoftware.Steam#651 is merged and a new version of Steam Flatpak is out.

Protontricks on Flatpak is published as an [extension to the Steam Flatpak](https://github.com/flathub/com.valvesoftware.Steam/blob/master/com.valvesoftware.Steam.yml#L101), which explains the name. Protontricks requires additional work in this case (such as the shell alias) since it's not a graphical application unlike most of the applications in Flathub, and also relies on another Flatpak application rather than being an application of its own.

**Comment by guihkx** [comment]
Since protontricks is working just fine again, I think this one can be closed.
