### ISSUE TITLE
Unable to install quartz

### ISSUE THREAD

**Issue by dariox86** [flathub/com.valvesoftware.Steam.Utility.protontricks#21]
When installing quartz, winetricks complains about missing "perl" command in row 1087 and when downloading windows6.1-KB976932-X86.exe and windows6.1-KB976932-X86.exe, both needed for quartz, these files are 0 byte in size. They must be downloaded separately and copied in the expected path. If you are unable to reproduce the issue I can supply a log.

**Comment by Matoking** [comment]
Winetricks tries to parse download progress if you're using the GUI. Perl wasn't included in the Flatpak image since [it was not needed at the time](https://github.com/Matoking/protontricks/issues/32#issuecomment-552107087).

I'll look into updating Flatpak with a Perl installation, but as a workaround you can try running Protontricks commands without the `--gui` flag if possible.

**Comment by dariox86** [comment]
As a workaround I commented the lines with Perl.

**Comment by Matoking** [comment]
I've published a newer build of Protontricks with Perl installed. Please try updating and check back if there are any lingering issues.

**Comment by dariox86** [comment]
Fixed. Works from GUI. Thank you.
