### ISSUE TITLE
warnings when using protontricks --gui

### ISSUE THREAD

**Issue by vatula** [flathub/com.valvesoftware.Steam.Utility.protontricks#9]
On a vanilla Fedora 31 when starting flatpak protontricks with --gui flag I get

```
 ------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Gtk-Message: 22:54:59.950: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:54:59.950: Failed to load module "pk-gtk-module"
Gtk-Message: 22:54:59.951: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:54:59.951: Failed to load module "pk-gtk-module"
```

**Comment by Matoking** [comment]
The "64-bit WINEPREFIX" warning is completely normal and to be expected.

Those GTK messages happen with the Steam Flatpak itself as well in my case but in either case there seem to be no issues besides the messages being annoying. Since the Flatpak version of Protontricks runs on top of the Steam Flatpak those warnings would need to be fixed there, if they can be fixed.

**Comment by vatula** [comment]
Got it. Thank you for an explanation.
